s1 = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(s1))
print('Está em maiusculo? ', s1.isupper())
print('É um número? ', s1.isnumeric())
print('É o que? ', s1.isalnum())
print('É uma letra? ', s1.isalpha())
